version: "3"
services: 
  app:
    build: .
    ports:
      - 3000:4000
    volumes: 
      - ./:/app
  db:
    image: postgres
    env_file: 
      - database.env
    volumes: 
      - ./public/db://var/lib/postgresql/data/
    ports:
      - 5432:5432
